// core/TelegramProvider.tsx
import { PropsWithChildren, ReactElement, useEffect, useMemo } from "react";
import createStyleConfig from "./config/configStyleTelegram";
import {
  Options,
  createSystemContextValue,
  defaultOptions,
  telegramAppGlobal,
} from "./config/configTelegram";
import {
  optionsContext,
  systemContext,
  telegramAppContext,
} from "./config/telegramContext";
import useAsyncMode from "./config/useAsyncMode";

export type WebAppProviderProps = PropsWithChildren<{
  options?: Options;
}>;

const TelegramProvider = ({
  children,
  options,
}: WebAppProviderProps): ReactElement => {
  const isLoadedWithAsyncMode = useAsyncMode(!!options?.async);
  const mergedOptions = useMemo(
    () => ({
      ...defaultOptions,
      ...options,
    }),
    [options]
  );
  const systemValue = useMemo(createSystemContextValue, []);
  const globalWebApp = useMemo(telegramAppGlobal, [isLoadedWithAsyncMode]);

  //edit---------------------
  useEffect(() => {
    createStyleConfig();
    telegramAppGlobal().MainButton.show();
    telegramAppGlobal().BackButton.show();
  }, [globalWebApp]);
  //Не должен знать о подключении кнопок-----------------

  useEffect(() => {
    if (!options?.smoothButtonsTransition) return;
    const forceHideButtons = () => {
      globalWebApp?.MainButton?.hide();
      globalWebApp?.BackButton?.hide();
    };

    window.addEventListener("beforeunload", forceHideButtons);
    return () => window.removeEventListener("beforeunload", forceHideButtons);
  }, [globalWebApp, options?.smoothButtonsTransition]);

  return (
    <systemContext.Provider value={systemValue}>
      <telegramAppContext.Provider value={globalWebApp}>
        <optionsContext.Provider value={mergedOptions}>
          {children}
        </optionsContext.Provider>
      </telegramAppContext.Provider>
    </systemContext.Provider>
  );
};
export default TelegramProvider;

// core/TelegramProvider.vue
<template>
  <system-context-provider :value="systemValue">
    <telegram-app-context-provider :value="globalWebApp">
      <options-context-provider :value="mergedOptions">
        <slot></slot>
      </options-context-provider>
    </telegram-app-context-provider>
  </system-context-provider>
</template>

<script>
import { computed, onMounted, watch } from "vue";
import createStyleConfig from "./config/configStyleTelegram";
import {
  createSystemContextValue,
  defaultOptions,
  telegramAppGlobal,
} from "./config/configTelegram";
import useAsyncMode from "./config/useAsyncMode";

export default {
  name: "TelegramProvider",
  props: {
    options: {
      type: Object,
      default: () => ({}),
    },
  },
  setup(props, { slots }) {
    const isLoadedWithAsyncMode = useAsyncMode(!!props.options?.async);

    const mergedOptions = computed(() => {
      return {
        ...defaultOptions,
        ...props.options,
      };
    });

    const systemValue = computed(() => createSystemContextValue());
    const globalWebApp = computed(() => telegramAppGlobal());

    // Side effects
    onMounted(() => {
      createStyleConfig();
      globalWebApp.value.MainButton.show();
      globalWebApp.value.BackButton.show();
    });

    watch(globalWebApp, (newValue) => {
      if (props.options?.smoothButtonsTransition) {
        const forceHideButtons = () => {
          newValue.MainButton.hide();
          newValue.BackButton.hide();
        };

        window.addEventListener("beforeunload", forceHideButtons);
        return () =>
          window.removeEventListener("beforeunload", forceHideButtons);
      }
    });

    return {
      systemValue,
      globalWebApp,
      mergedOptions,
    };
  },
};
</script>
